### ISSUE TITLE
Fix probe positions entry

### ISSUE THREAD

**Issue by kjy5** [VirtualBrainLab/NPTrajectoryPlanner#105]
`ManualCoordinateEntry` is not behaving well to set probe position. It gets confused when given CCF space coordinates

**Comment by dbirman** [comment]
- [ ] Refactor to SetProbePositionCCF
- [ ] Add SetProbePositionInVivo
- [ ] Figure out whether we need other alternate position setting options

**Comment by dbirman** [comment]
14d4a186b83a3959420a14b463adf344417cfb75
