### ISSUE TITLE
UI things to fix

### ISSUE THREAD

**Issue by kjy5** [VirtualBrainLab/NPTrajectoryPlanner#148]
Various UI things we need to implement

- [x] ~~Question mark help button describing manipulator handedness~~ #156 
- [x] Make it obvious when a value has been applied in the Sensapex settings (checkmarks or text)
  - [x] "Connect to" vs "connected to" on server connect
- [x] Make handedness dropdown automatically apply settings
- [x] Dropdown widget scaling and scrolling
- [x] Capture scrolling only when focused on game
  - [x] Find better user input capturing system (to avoid reacting to input while user is not focused on game)

**Comment by kjy5** [comment]
This is in addition to #142

**Comment by dbirman** [comment]
- [ ] Fix all dropdown menus to render properly when open

**Comment by kjy5** [comment]
^ Already in list!

**Comment by dbirman** [comment]
Actually lets put handedness on the docs, images are here: https://github.com/VirtualBrainLab/vbl-docs/tree/main/source/_static/images
