### ISSUE TITLE
fonts difficult to read

### ISSUE THREAD

**Issue by nsteinme** [VirtualBrainLab/NPTrajectoryPlanner#40]
Would be great to have ability to increase the font size. The contrast is also really low and difficult to read: 
<img width="89" alt="image" src="https://user-images.githubusercontent.com/7590975/157294594-586df3ba-7b79-4b4d-a34f-385c15436a57.png">

**Comment by dbirman** [comment]
@dbirman Add high contrast settings as an optional flag?
- [ ] Font size 
- [ ] Lighter gray background in settings panels

**Comment by dbirman** [comment]
Fixed in v0.7 with UI overhaul
