### ISSUE TITLE
Probes spawn in with a green-ish color regardless of their actual color

### ISSUE THREAD

**Issue by kjy5** [VirtualBrainLab/NPTrajectoryPlanner#439]
A probe could have a blue or orange color, but the material on it is a dark green. If you choose a new color it will then update properly.

Reproduce this by dropping a new probe into the scene and notice that it is not the same color as what is shown in the quick settings panel.

**Comment by kjy5** [comment]
#446

**Comment by kjy5** [comment]
Can't change `_color` to `Color` because it affects downstream code.

**Comment by dbirman** [comment]
0280328b7f0a6a3897b6fdf75c912ca3c31c7dfc
