### ISSUE TITLE
Sensapex uMp-3 support

### ISSUE THREAD

**Issue by kjy5** [VirtualBrainLab/NPTrajectoryPlanner#458]

**Comment by 20180220** [comment]
I am not sure asking this here is appropriate but is uMp-3-NP supported by PinPoint Software? We tried to use it with the latest version v1.1.6 but it did nork. Please let me know if there is another version to download. I apologize if this is not appropriate.

**Comment by kjy5** [comment]
Hi @20180220 let's discuss it here: #684
