### ISSUE TITLE
Show hidden accounts insertions as a surface dot + depth line

### ISSUE THREAD

**Issue by kjy5** [VirtualBrainLab/NPTrajectoryPlanner#515]
- Enabling the full probe makes the scene too cluttered
- Hiding it entirely and not showing anything is too confusing (it's unclear where the insertion is going)

**Comment by dbirman** [comment]
https://github.com/VirtualBrainLab/Pinpoint/issues/517

**Comment by kjy5** [comment]
Handled by #517
