### ISSUE TITLE
Steam Linux build might not be loading annotation dataset properly [review response]

### ISSUE THREAD

**Issue by dbirman** [VirtualBrainLab/NPTrajectoryPlanner#565]
Should be fixed as soon as BrainAtlas is imported

**Comment by dbirman** [comment]
I think that I just didn't build the 3D data, which is now built -- will need to test on a linux machine

**Comment by kjy5** [comment]
Seems to be working fine on Steam Deck?

**Comment by dbirman** [comment]
Yep thanks!
