### ISSUE TITLE
Share coordinates

### ISSUE THREAD

**Issue by RobertoDF** [VirtualBrainLab/NPTrajectoryPlanner#581]
HI!
Share links work only immediately after creation. What is the best way to share a set of coordinates longer term? For example this is a [link](https://data.virtualbrainlab.org/Pinpoint/?Probes=eyJBUE1MRFYiOnsieCI6MS4xMjY0MTkzMDU4MDEzOTE3LCJ5IjotMC40NTk4MjM1NDg3OTM3OTI3LCJ6IjotNC4yOTIxOTUzMjAxMjkzOTQ5fSwiQW5nbGVzIjp7IngiOjAuMCwieSI6MC4wLCJ6IjowLjB9LCJDb29yZFNwYWNlTmFtZSI6IkNDRiIsIkNvb3JkVHJhbnNmb3JtTmFtZSI6IlFpdTIwMTgiLCJaZXJvQ29vcmRPZmZzZXQiOnsieCI6MC4wLCJ5IjowLjAsInoiOjAuMCwidyI6MC4wfSwiU2VsZWN0aW9uTGF5ZXJOYW1lIjoiZGVmYXVsdCIsIlR5cGUiOjAsIkNvbG9yIjp7InIiOjAuNTgwMzkyMTgxODczMzIxNSwiZyI6MC40MDM5MjE1NzQzNTQxNzE3OCwiYiI6MC43NDExNzY0ODYwMTUzMTk4LCJhIjoxLjB9LCJVVUlEIjoiYzBkOGFjY2QtNTQ0MC00ZWZlLTg0OTgtM2QwNjMzM2QxOTU4IiwiTmFtZSI6IkFDQSIsIkFQSVRhcmdldCI6IiIsIk1hbmlwdWxhdG9yVHlwZSI6IiIsIk1hbmlwdWxhdG9ySUQiOiIiLCJCcmFpblN1cmZhY2VPZmZzZXQiOjAuMCwiRHJvcDJTdXJmYWNlV2l0aERlcHRoIjp0cnVlLCJJc1JpZ2h0SGFuZGVkIjpmYWxzZX07eyJBUE1MRFYiOnsieCI6LTEuMDA5MDA3NDUzOTE4NDU3LCJ5IjotMS42NzE2MzU4NjYxNjUxNjEyLCJ6IjotNC4zNDk3MDc2MDM0NTQ1OX0sIkFuZ2xlcyI6eyJ4IjotMjA4LjAwNTA2NTkxNzk2ODc2LCJ5IjoyOS4wLCJ6IjowLjB9LCJDb29yZFNwYWNlTmFtZSI6IkNDRiIsIkNvb3JkVHJhbnNmb3JtTmFtZSI6IlFpdTIwMTgiLCJaZXJvQ29vcmRPZmZzZXQiOnsieCI6MC4wLCJ5IjowLjAsInoiOjAuMCwidyI6MC4wfSwiU2VsZWN0aW9uTGF5ZXJOYW1lIjoiZGVmYXVsdCIsIlR5cGUiOjAsIkNvbG9yIjp7InIiOjAuMTcyNTQ5MDI0MjI0MjgxMywiZyI6MC42Mjc0NTEwMDI1OTc4MDg4LCJiIjowLjE3MjU0OTAyNDIyNDI4MTMsImEiOjEuMH0sIlVVSUQiOiIwMWUzMWM5Yi02ODZmLTQzY2UtYmQ1NS05NzUyOGFjMWExNzciLCJOYW1lIjoiU1MiLCJBUElUYXJnZXQiOiIiLCJNYW5pcHVsYXRvclR5cGUiOiIiLCJNYW5pcHVsYXRvcklEIjoiIiwiQnJhaW5TdXJmYWNlT2Zmc2V0IjowLjAsIkRyb3AyU3VyZmFjZVdpdGhEZXB0aCI6dHJ1ZSwiSXNSaWdodEhhbmRlZCI6ZmFsc2V9O3siQVBNTERWIjp7IngiOi0yLjk3MDE0MjEyNjA4MzM3NCwieSI6LTEuNTg2NDAzMDEyMjc1Njk1OSwieiI6LTQuNTU5ODA5Njg0NzUzNDE4fSwiQW5nbGVzIjp7IngiOjY3LjI4OTk5MzI4NjEzMjgxLCJ5IjozMS41MTUwMTA4MzM3NDAyMzYsInoiOjAuMH0sIkNvb3JkU3BhY2VOYW1lIjoiQ0NGIiwiQ29vcmRUcmFuc2Zvcm1OYW1lIjoiUWl1MjAxOCIsIlplcm9Db29yZE9mZnNldCI6eyJ4IjowLjAsInkiOjAuMCwieiI6MC4wLCJ3IjowLjB9LCJTZWxlY3Rpb25MYXllck5hbWUiOiJkZWZhdWx0IiwiVHlwZSI6MCwiQ29sb3IiOnsiciI6MS4wLCJnIjowLjQ5ODAzOTIxNTgwMzE0NjM5LCJiIjowLjA1NDkwMTk2MTIzNzE5MjE1NywiYSI6MS4wfSwiVVVJRCI6IjQzZTA4NmQ1LWQwMjMtNDc0OS1iNjE3LTI5N2ViNTJlNGYwYiIsIk5hbWUiOiJWSVMgMi) I created yesterday that now is just empty.

**Comment by dbirman** [comment]
Hmm, that's strange... do you happen to know exactly what was in the scene when you created this share link?

If I quickly throw together a basic scene with just a single probe in it, the [link](https://data.virtualbrainlab.org/Pinpoint/?Probes=eyJBUE1MRFYiOnsieCI6MS4xNjAzNTUzMjk1MTM1NDk5LCJ5IjotNi42ODA1OTEwMTM3MTkwOTVlLTgsInoiOi00LjMzMDUwMzk0MDU4MjI3NX0sIkFuZ2xlcyI6eyJ4IjowLjAsInkiOjE1LjAsInoiOjAuMH0sIkNvb3JkU3BhY2VOYW1lIjoiQ0NGIiwiQ29vcmRUcmFuc2Zvcm1OYW1lIjoiUWl1MjAxOCIsIlplcm9Db29yZE9mZnNldCI6eyJ4IjowLjAsInkiOjAuMCwieiI6MC4wLCJ3IjowLjB9LCJTZWxlY3Rpb25MYXllck5hbWUiOiJkZWZhdWx0IiwiVHlwZSI6MCwiQ29sb3IiOnsiciI6MC4xMjE1Njg2Mjc2NTU1MDYxNCwiZyI6MC40NjY2NjY2Njg2NTM0ODgxOCwiYiI6MC43MDU4ODIzNzA0NzE5NTQ0LCJhIjoxLjB9LCJVVUlEIjoiYTU4OGViYWQtMWU2ZC00ZWI3LThlOGEtOThiOWU4OWZjYWI0IiwiTmFtZSI6Ik1TLWE1ODhlYmFkIiwiQVBJVGFyZ2V0IjoiIiwiTWFuaXB1bGF0b3JUeXBlIjoiIiwiTWFuaXB1bGF0b3JJRCI6IiIsIkJyYWluU3VyZmFjZU9mZnNldCI6MC4wLCJEcm9wMlN1cmZhY2VXaXRoRGVwdGgiOnRydWUsIklzUmlnaHRIYW5kZWQiOmZhbHNlfQ==&Settings=eyJTaG93U3VyZmFjZUNvb3JkIjp0cnVlLCJTaG93SW5QbGFuZVNsaWNlIjp0cnVlLCJHaG9zdEluYWN0aXZlUHJvYmVzIjp0cnVlLCJHaG9zdEluYWN0aXZlQXJlYXMiOmZhbHNlLCJVbml0c0luVU0iOnRydWUsIlNob3dBbGxQcm9iZVBhbmVscyI6dHJ1ZSwiUHJvYmVQYW5lbEhlaWdodCI6MTQ0MC4wLCJEZXRlY3RDb2xsaXNpb25zIjp0cnVlLCJSb3RhdGVBUE1MMlByb2JlQXhpcyI6ZmFsc2UsIlByb2JlU3BlZWQiOjIsIlNob3dBdGxhczNEU2xpY2VzIjowLCJSZWxhdGl2ZUNvb3JkIjp7IngiOjUuNDAwMDAwMDk1MzY3NDMyLCJ5Ijo1LjY5OTk5OTgwOTI2NTEzNywieiI6MC4zMzE5OTk5ODczNjM4MTUzfSwiQWN0aXZlQ29vcmRpbmF0ZVRyYW5zZm9ybUluZGV4IjoxLCJCcmVnbWFMYW1iZGFEaXN0YW5jZSI6NC4xNTAwMDAwOTUzNjc0MzIsIkVwaHlzTGlua1NlcnZlcklQIjoiIiwiRXBoeXNMaW5rU2VydmVyUG9ydCI6ODA4MSwiRXBoeXNMaW5rUmlnaHRIYW5kZWRNYW5pcHVsYXRvcnMiOiIiLCJBY2NvdW50c0xvZ2luVG9nZ2xlIjp0cnVlLCJPcGVuRXBoeXNBUElUb2dnbGUiOmZhbHNlLCJPcGVuRXBoeXNBUElUYXJnZXQiOiJodHRwOi8vbG9jYWxob3N0OjM3NDk3IiwiU3Bpa2VHTFhBUElUb2dnbGUiOmZhbHNlLCJTcGlrZUdMWEFQSVRhcmdldCI6IjEyNy4wLjAuMTo0MTQyIiwiU3Bpa2VHTFhIZWxsb1BhdGgiOiJDOlxcSGVsbG9TR0xYLXdpblxcSGVsbG9TR0xYLmV4ZSIsIkFQSVVwZGF0ZVJhdGUiOjEwLjAsIlVzZUlCTEFuZ2xlcyI6ZmFsc2UsIkF4aXNDb250cm9sIjp0cnVlLCJVc2VBY3JvbnltcyI6dHJ1ZSwiVXNlQmVyeWwiOnRydWUsIkNhbWVyYVpvb20iOjEyLjAsIkNhbWVyYVJvdGF0aW9uIjp7IngiOjguMTAwMDAwMzgxNDY5NzI3LCJ5IjotMzQuOTk5OTk2MTg1MzAyNzM3LCJ6IjowLjB9fQ==) seems to work fine

When I load your link Pinpoint is complaining that there is an invalid character in that string. Is it possible it got copied through some kind of text editor, email or somewhere else? Or is that a direct copy from the "share" button?

Should be easy to fix once I can find the issue, thanks for flagging this!

**Comment by RobertoDF** [comment]
Thanks for the quick answer!
It was a direct copy from the share button.. and this is the content
<img width="861" alt="Screenshot 2023-11-02 at 15 18 05" src="https://github.com/VirtualBrainLab/Pinpoint/assets/37729096/32f8868a-1d3b-46fd-864d-57f17148fa71">

if I load the scene from my account and create a link now, it does work, see [here](https://data.virtualbrainlab.org/Pinpoint/?Probes=eyJBUE1MRFYiOnsieCI6MS4xMjY0MTkzMDU4MDEzOTE3LCJ5IjotMC40NTk4MjQ4ODk4OTgzMDAxOSwieiI6LTQuMjkyMTk1MzIwMTI5Mzk0OX0sIkFuZ2xlcyI6eyJ4IjowLjAsInkiOjAuMCwieiI6MC4wfSwiQ29vcmRTcGFjZU5hbWUiOiJDQ0YiLCJDb29yZFRyYW5zZm9ybU5hbWUiOiJRaXUyMDE4IiwiWmVyb0Nvb3JkT2Zmc2V0Ijp7IngiOjAuMCwieSI6MC4wLCJ6IjowLjAsInciOjAuMH0sIlNlbGVjdGlvbkxheWVyTmFtZSI6ImRlZmF1bHQiLCJUeXBlIjowLCJDb2xvciI6eyJyIjowLjU4MDM5MjE4MTg3MzMyMTUsImciOjAuNDAzOTIxNTc0MzU0MTcxNzgsImIiOjAuNzQxMTc2NDg2MDE1MzE5OCwiYSI6MS4wfSwiVVVJRCI6ImMwZDhhY2NkLTU0NDAtNGVmZS04NDk4LTNkMDYzMzNkMTk1OCIsIk5hbWUiOiJBQ0EiLCJBUElUYXJnZXQiOiIiLCJNYW5pcHVsYXRvclR5cGUiOiIiLCJNYW5pcHVsYXRvcklEIjoiIiwiQnJhaW5TdXJmYWNlT2Zmc2V0IjowLjAsIkRyb3AyU3VyZmFjZVdpdGhEZXB0aCI6dHJ1ZSwiSXNSaWdodEhhbmRlZCI6ZmFsc2V9O3siQVBNTERWIjp7IngiOi0yLjk3MDE0NDAzMzQzMjAwNywieSI6LTEuNTg2NDAyNzczODU3MTE2OCwieiI6LTQuNTU5ODA4NzMxMDc5MTAyfSwiQW5nbGVzIjp7IngiOjY3LjI4OTk5MzI4NjEzMjgxLCJ5IjozMS41MTUwMTA4MzM3NDAyMzYsInoiOjAuMH0sIkNvb3JkU3BhY2VOYW1lIjoiQ0NGIiwiQ29vcmRUcmFuc2Zvcm1OYW1lIjoiUWl1MjAxOCIsIlplcm9Db29yZE9mZnNldCI6eyJ4IjowLjAsInkiOjAuMCwieiI6MC4wLCJ3IjowLjB9LCJTZWxlY3Rpb25MYXllck5hbWUiOiJkZWZhdWx0IiwiVHlwZSI6MCwiQ29sb3IiOnsiciI6MS4wLCJnIjowLjQ5ODAzOTIxNTgwMzE0NjM5LCJiIjowLjA1NDkwMTk2MTIzNzE5MjE1NywiYSI6MS4wfSwiVVVJRCI6IjQzZTA4NmQ1LWQwMjMtNDc0OS1iNjE3LTI5N2ViNTJlNGYwYiIsIk5hbWUiOiJWSVMgMiIsIkFQSVRhcmdldCI6IiIsIk1hbmlwdWxhdG9yVHlwZSI6IiIsIk1hbmlwdWxhdG9ySUQiOiIiLCJCcmFpblN1cmZhY2VPZmZzZXQiOjAuMCwiRHJvcDJTdXJmYWNlV2l0aERlcHRoIjp0cnVlLCJJc1JpZ2h0SGFuZGVkIjpmYWxzZX07eyJBUE1MRFYiOnsieCI6LTEuMDA5MDEwNDM0MTUwNjk1OSwieSI6LTEuNjcxNjQxMjMwNTgzMTkxLCJ6IjotNC4zNDk3MDgwODAyOTE3NDh9LCJBbmdsZXMiOnsieCI6LTIwOC4wMDUwNjU5MTc5Njg3NiwieSI6MjkuMCwieiI6MC4wfSwiQ29vcmRTcGFjZU5hbWUiOiJDQ0YiLCJDb29yZFRyYW5zZm9ybU5hbWUiOiJRaXUyMDE4IiwiWmVyb0Nvb3JkT2Zmc2V0Ijp7IngiOjAuMCwieSI6MC4wLCJ6IjowLjAsInciOjAuMH0sIlNlbGVjdGlvbkxheWVyTmFtZSI6ImRlZmF1bHQiLCJUeXBlIjowLCJDb2xvciI6eyJyIjowLjE3MjU0OTAyNDIyNDI4MTMsImciOjAuNjI3NDUxMDAyNTk3ODA4OCwiYiI6MC4xNzI1NDkwMjQyMjQyODEzLCJhIjoxLjB9LCJVVUlEIjoiMDFlMzFjOWItNjg2Zi00M2NlLWJkNTUtOTc1MjhhYzFhMTc3IiwiTmFtZSI6IlNTIiwiQVBJVGFyZ2V0IjoiIiwiTWFuaXB1bGF0b3JUeXBlIjoiIiwiTWFuaXB1bGF0b3JJRCI6IiIsIkJyYWluU3VyZmFjZU9mZnNldCI6MC4wLCJEcm9wMlN1cmZhY2VXaXRoRGVwdGgiOnRydWUsIklzUmlnaHRIYW5kZWQiOmZhbHNlfTt7IkFQTUxEViI6eyJ4IjotMi4xMDQwMjc5ODY1MjY0ODk0LCJ5IjotMi4wMDMyMDM2MzA0NDczODc5LCJ6IjotNC4wMTk0OTY5MTc3MjQ2MDl9LCJBbmdsZXMiOnsieCI6MC4wLCJ5IjoyNS4wLCJ6IjowLjB9LCJDb29yZFNwYWNlTmFtZSI6IkNDRiIsIkNvb3JkVHJhbnNmb3JtTmFtZSI6IlFpdTIwMTgiLCJaZXJvQ29vcmRPZmZzZXQiOnsieCI6MC4wLCJ5IjowLjAsInoiOjAuMCwidyI6MC4wfSwiU2VsZWN0aW9uTGF5ZXJOYW1lIjoiZGVmYXVsdCIsIlR5cGUiOjAsIkNvbG9yIjp7InIiOjAuODM5MjE1Njk1ODU4MDAxNywiZyI6MC4xNTI5NDExODIyNTU3NDQ5NCwiYiI6MC4xNTY4NjI3NTA2NDk0NTIyLCJhIjoxLjB9LCJVVUlEIjoiNmRhMzQyZTktYjAzZS00OTUwLTlhNmEtYmE0YjkyY2EzNmQ5IiwiTmFtZSI6IlZJUyIsIkFQSVRhcmdldCI6IiIsIk1hbmlwdWxhdG9yVHlwZSI6IiIsIk1hbmlwdWxhdG9ySUQiOiIiLCJCcmFpblN1cmZhY2VPZmZzZXQiOjAuMCwiRHJvcDJTdXJmYWNlV2l0aERlcHRoIjp0cnVlLCJJc1JpZ2h0SGFuZGVkIjpmYWxzZX07eyJBUE1MRFYiOnsieCI6LTIuNDg3ODU5NzI1OTUyMTQ4NiwieSI6LTQuNzc1NjAyMzQwNjk4MjQyLCJ6IjotMi43NjkzMjg4MzI2MjYzNDI5fSwiQW5nbGVzIjp7IngiOi03NS41NTUwMjMxOTMzNTkzOCwieSI6NTAuMCwieiI6MC4wfSwiQ29vcmRTcGFjZU5hbWUiOiJDQ0YiLCJDb29yZFRyYW5zZm9ybU5hbWUiOiJRaXUyMDE4IiwiWmVyb0Nvb3JkT2Zmc2V0Ijp7IngiOjAuMCwieSI6MC4wLCJ6IjowLjAsInciOjAuMH0sIlNlbGVjdGlvbkxheWVyTmFtZSI6ImRlZmF1bHQiLCJUeXBlIjowLCJDb2xvciI6eyJyIjowLjY4MjM1Mjk2MDEwOTcxMDcsImciOjAuNzgwMzkyMTY5OTUyMzkyNiwiYiI6MC45MDk4MDM5MjY5NDQ3MzI3LCJhIjoxLjB9LCJVVUlEIjoiZWU3NzVjOWQtNWMzNi00OThmLTgwYzItMjk4NGRiYjM4YjBhIiwiTmFtZSI6IlZJUy9BVUQiLCJBUElUYXJnZXQiOiIiLCJNYW5pcHVsYXRvclR5cGUiOiIiLCJNYW5pcHVsYXRvcklEIjoiIiwiQnJhaW5TdXJmYWNlT2Zmc2V0IjowLjAsIkRyb3AyU3VyZmFjZVdpdGhEZXB0aCI6dHJ1ZSwiSXNSaWdodEhhbmRlZCI6ZmFsc2V9O3siQVBNTERWIjp7IngiOi0yLjM4NDAyNjI4ODk4NjIwNiwieSI6LTQuODIyOTI3OTUxODEyNzQ0LCJ6IjotMy4wMzk3NzY1NjM2NDQ0MDl9LCJBbmdsZXMiOnsieCI6LTEyMi40NzY4MjE4OTk0MTQwNiwieSI6NTUuMCwieiI6MC4wfSwiQ29vcmRTcGFjZU5hbWUiOiJDQ0YiLCJDb29yZFRyYW5zZm9ybU5hbWUiOiJRaXUyMDE4IiwiWmVyb0Nvb3JkT2Zmc2V0Ijp7IngiOjAuMCwieSI6MC4wLCJ6IjowLjAsInciOjAuMH0sIlNlbGVjdGlvbkxheWVyTmFtZSI6ImRlZmF1bHQiLCJUeXBlIjowLCJDb2xvciI6eyJyIjoxLjAsImciOjAuNzMzMzMzMzQ5MjI3OTA1MywiYiI6MC40NzA1ODgyMzcwNDcxOTU0NiwiYSI6MS4wfSwiVVVJRCI6IjAwM2I1YTE4LTk4ZTUtNDY2Yi1iOTNkLTExOGY0MjJiOTJjNiIsIk5hbWUiOiJBVUQiLCJBUElUYXJnZXQiOiIiLCJNYW5pcHVsYXRvclR5cGUiOiIiLCJNYW5pcHVsYXRvcklEIjoiIiwiQnJhaW5TdXJmYWNlT2Zmc2V0IjowLjAsIkRyb3AyU3VyZmFjZVdpdGhEZXB0aCI6dHJ1ZSwiSXNSaWdodEhhbmRlZCI6ZmFsc2V9&Settings=eyJTaG93U3VyZmFjZUNvb3JkIjp0cnVlLCJTaG93SW5QbGFuZVNsaWNlIjpmYWxzZSwiR2hvc3RJbmFjdGl2ZVByb2JlcyI6ZmFsc2UsIkdob3N0SW5hY3RpdmVBcmVhcyI6ZmFsc2UsIlVuaXRzSW5VTSI6dHJ1ZSwiU2hvd0FsbFByb2JlUGFuZWxzIjp0cnVlLCJQcm9iZVBhbmVsSGVpZ2h0IjoxNDM0LjAsIkRldGVjdENvbGxpc2lvbnMiOnRydWUsIlJvdGF0ZUFQTUwyUHJvYmVBeGlzIjp0cnVlLCJQcm9iZVNwZWVkIjoxLCJTaG93QXRsYXMzRFNsaWNlcyI6MCwiUmVsYXRpdmVDb29yZCI6eyJ4Ijo1LjQwMDAwMDA5NTM2NzQzMiwieSI6NS42OTk5OTk4MDkyNjUxMzcsInoiOjAuMzMxOTk5OTg3MzYzODE1M30sIkFjdGl2ZUNvb3JkaW5hdGVUcmFuc2Zvcm1JbmRleCI6MSwiQnJlZ21hTGFtYmRhRGlzdGFuY2UiOjQuMTUwMDAwMDk1MzY3NDMyLCJFcGh5c0xpbmtTZXJ2ZXJJUCI6IiIsIkVwaHlzTGlua1NlcnZlclBvcnQiOjgwODEsIkVwaHlzTGlua1JpZ2h0SGFuZGVkTWFuaXB1bGF0b3JzIjoiIiwiQWNjb3VudHNMb2dpblRvZ2dsZSI6dHJ1ZSwiT3BlbkVwaHlzQVBJVG9nZ2xlIjpmYWxzZSwiT3BlbkVwaHlzQVBJVGFyZ2V0IjoiaHR0cDovL2xvY2FsaG9zdDozNzQ5NyIsIlNwaWtlR0xYQVBJVG9nZ2xlIjpmYWxzZSwiU3Bpa2VHTFhBUElUYXJnZXQiOiIxMjcuMC4wLjE6NDE0MiIsIlNwaWtlR0xYSGVsbG9QYXRoIjoiQzpcXEhlbGxvU0dMWC13aW5cXEhlbGxvU0dMWC5leGUiLCJBUElVcGRhdGVSYXRlIjoxMC4wLCJVc2VJQkxBbmdsZXMiOmZhbHNlLCJBeGlzQ29udHJvbCI6dHJ1ZSwiVXNlQWNyb255bXMiOnRydWUsIlVzZUJlcnlsIjp0cnVlLCJDYW1lcmFab29tIjo5LjUsIkNhbWVyYVJvdGF0aW9uIjp7IngiOjMuMTAwMDM3ODEzMTg2NjQ1NywieSI6Ni4xNzQ5NDA1ODYwOTAwODgsInoiOjAuMH19). However tomorrow it will become empty, at least this is what happened in the past days.

**Comment by dbirman** [comment]
Wow that is super mysterious. I'll start investigating...

**Comment by RobertoDF** [comment]
Ok the link works! Somehow if I create an hyperlink in a Word document the link stops working. This must be related to Word. Somehow the link gets modified........ I´ll close this.
