### ISSUE TITLE
Utilize UpdateSurfacePosition for surface calculations

### ISSUE THREAD

**Issue by kjy5** [VirtualBrainLab/NPTrajectoryPlanner#594]
After #588 
- Implement DV and depth in `UpdateSurfacePosition`
- use `UpdateSurfacePosition` to get the surface position in Copilot code and drop to surface code

**Comment by dbirman** [comment]
Bug that was preventing working on this fixed in 00421b9ffb23af044c14bf363baf12bcf8e6a052
