### ISSUE TITLE
Pinpoint anatomy doesn't match on probe viewer (SpikeGLX)

### ISSUE THREAD

**Issue by Virginia9733** [VirtualBrainLab/NPTrajectoryPlanner#613]
**Describe the bug**
Similar to the issue described here: https://github.com/VirtualBrainLab/Pinpoint/issues/611
It seems like PinPont's anatomy doesn't match the anatomy shown in the SpikeGLX IMRO table.

We updated the newest version of PinPoint.

Using Neuropixels 1.0: 
Anatomy in PinPoint looks like this:
![Screenshot 2023-12-14 150525](https://github.com/VirtualBrainLab/Pinpoint/assets/61534754/649d8a86-c79c-4510-8f3a-357524b1cb70)
But in SpikeGLX look like this:
![10](https://github.com/VirtualBrainLab/Pinpoint/assets/61534754/949aab62-6b17-435d-b080-461daf9bdc28)

Using Neuropixels 2.0: 
Anatomy in PinPoint looks like this:
![Screenshot 2023-12-13 234253](https://github.com/VirtualBrainLab/Pinpoint/assets/61534754/7daca5f7-51a3-4f11-86b9-b0f37316542e)
But in SpikeGLX look like this:
![4](https://github.com/VirtualBrainLab/Pinpoint/assets/61534754/45ebcbba-bb69-4667-bc4b-5b60ad86b1c7)

Anatomy in PinPoint looks like this:
![Screenshot 2023-12-14 003051](https://github.com/VirtualBrainLab/Pinpoint/assets/61534754/2e165634-96ce-4d20-9d66-cd95db500536)
But in SpikeGLX look like this:
![8](https://github.com/VirtualBrainLab/Pinpoint/assets/61534754/ac380800-d868-4a22-b21e-503435f03516)

Looking forward to hearing from you.

**Comment by dbirman** [comment]
Thanks this is a known issue, we'll have it fixed in early January.

In the meantime, if you're on Steam we have a beta branch that is tagged to an older version (v0.9) which should work properly. You can also download older Windows releases from Github directly, e.g. this one: https://github.com/VirtualBrainLab/Pinpoint/releases/tag/v0.9.7

#611 
#602

**Comment by dbirman** [comment]
Partial fix on 1.1.1 d9005396e023259414958cc6cb98bd45b437bfe8

**Comment by dbirman** [comment]
Fixed, pending 1.1.1 f42fe54d566043bd632991727fa15833b35596ca
