### ISSUE TITLE
Channel maps don't auto re-expand when there is space

### ISSUE THREAD

**Issue by kjy5** [VirtualBrainLab/NPTrajectoryPlanner#627]
Example situation (done manually):
1. Add a 2.4 probe: 

![Image](https://github.com/VirtualBrainLab/Pinpoint/assets/82800265/41eaae7d-1799-4f0b-8e1b-17cde08242e8)

2. Add a 1.0 probe (the channel maps resize accordingly): 

![Image](https://github.com/VirtualBrainLab/Pinpoint/assets/82800265/8b67e886-31ad-416f-bfb3-1765ac0c9bbc)

3. Remove the 2.4 probe:

![Image](https://github.com/VirtualBrainLab/Pinpoint/assets/82800265/59de795d-1e15-4cbe-9030-038743995c1c)

The 1.0 probe channel maps does not resize to full height.

**Comment by dbirman** [comment]
fea806039d498f7c4ecb0d7427ce973ee303202d
