### ISSUE TITLE
Bregma coordinate is not defaulting correctly when PlayerPrefs gets reset

### ISSUE THREAD

**Issue by dbirman** [VirtualBrainLab/NPTrajectoryPlanner#636]

**Comment by kjy5** [comment]
Is this where it starts at 0,0,0?

**Comment by dbirman** [comment]
Yeah it should default to the `Utils.BregmaDefault[atlasName]` value but for some reason it's either not getting loaded or getting over-written on a clean load

**Comment by dbirman** [comment]
a515adf6e5a1bffd3433ad9e253b711d9b190ae5
