### ISSUE TITLE
add help text to website?

### ISSUE THREAD

**Issue by nsteinme** [VirtualBrainLab/NPTrajectoryPlanner#68]
Maybe some plain text that just says something like "Please be patient, screen will be black for ~10-20 seconds before loading the first time. If the interface appears but you don't see a brain, click one of the + buttons in bottom right to add a probe and it should appear. For further documentation and help, visit this page. To submit a bug report or feature request, visit this page." In a nice font ;)

**Comment by dbirman** [comment]
Added in v0.7
