### ISSUE TITLE
uMp-3-NP support

### ISSUE THREAD

**Issue by kjy5** [VirtualBrainLab/NPTrajectoryPlanner#684]
> I am not sure asking this here is appropriate but is uMp-3-NP supported by PinPoint Software? We tried to use it with the latest version v1.1.6 but it did nork. Please let me know if there is another version to download. I apologize if this is not appropriate.

_Originally posted by @20180220 in https://github.com/VirtualBrainLab/Pinpoint/issues/458#issuecomment-2089981943_

**Comment by kjy5** [comment]
@20180220 Could you describe your setup and what didn't work for you?

**Comment by 20180220** [comment]
Thank you very much for your reply.
Well, we simply tried to use Pinpoint softwware v1.1.6. with  a uMp-3-NP Manipulator of Multiprobe rig (Sensapex),
but we could not connect the software with it. We were able to do so with uMp-4. 
![pinpoint](https://github.com/VirtualBrainLab/Pinpoint/assets/168723023/f586de6e-55ae-448f-baf3-b4140d982255)
The messages we got in the software were different, so I attached it for FYI. 
We really apprecaite your support.

Best Regards,

**Comment by kjy5** [comment]
Ok cool, thanks for the update and the error message. Assuming the image on the left is with a uMp-3, it looks like they did successfully connect but is running into trouble with further API calls. I will take a look at this and get back to you soon.

**Comment by 20180220** [comment]
yes, that is correct. The left one is the one which did not work. 
Thank you very much for your support! 
We really apprecaite it.

Best Regards,

**Comment by kjy5** [comment]
Hi, I've made a new patch release of Pinpoint that hopefully addresses this issue you are seeing. Please let me know if it works for you! Thank you!

https://github.com/VirtualBrainLab/Pinpoint/releases/tag/v1.1.7

**Comment by 20180220** [comment]
Hi, Thank you very muc for releasing the new version. 
We will try and let you know if it work!
Again, thank you!

**Comment by 20180220** [comment]
Hi, I have jsut tried it, and it worked!! Thank you very much for your support! 
We truely apprecaite it.

Best Regards,

**Comment by kjy5** [comment]
Sweet! So glad to hear this build fixed your issues. I'll close this issue for now but feel free to message back if you have any questions!

**Comment by 20180220** [comment]
Sure, I will. Again, thank you so much!
