### ISSUE TITLE
Ephys Link error

### ISSUE THREAD

**Issue by BlakeRussell98** [VirtualBrainLab/NPTrajectoryPlanner#687]
I am getting this error when trying to launch the server connection for ephys link. 
Player.log is saying that there is an error connecting to the local host
![image](https://github.com/VirtualBrainLab/Pinpoint/assets/117654757/ed4b3866-3ee7-4d0c-9a37-6a02077bb67d)
I never had this issue when I was using Sensapex's uMp-4 micromanipulators. But now we have upgraded our setup to Sensapex's multiprobe rig with uMp-3-NP micromanipulators (see attached picture for how the rig is wired up), I am getting this error.
![image](https://github.com/VirtualBrainLab/Pinpoint/assets/117654757/05024cea-e1ae-4a11-bdd1-04297e06cf54)

**Comment by dbirman** [comment]
I believe you need to launch ephys-link in uMP-3 mode, using `-t ump3` in the launch options, if you're launching from a terminal. Kenneth can clarify if that's the only problem here.

**Comment by kjy5** [comment]
It looks like Ephys Link was launched correctly from Pinpoint however your manipulators or not being detected. Does your setup work with uMp-4 manipulators? 

I'll investigate this error you have and update here soon.

**Comment by kjy5** [comment]
Hi Blake, I've published a patch fix to Pinpoint that might address your issue. You can download it from Steam or here: https://github.com/VirtualBrainLab/Pinpoint/releases/tag/v1.1.7. Let me know if it works!

The error you're getting seems to imply that the sensapex touch screen controllers themselves can't find your manipulators which is quite odd. I assume you are able to see them on the TSC? See if this new builds helps and we can go from there.

**Comment by BlakeRussell98** [comment]
The new build works! Thank you

**Comment by kjy5** [comment]
Sweet! Glad to hear the fix worked.
