### ISSUE TITLE
Is it possible to export the channel map on pinpoint

### ISSUE THREAD

**Issue by timsainb** [VirtualBrainLab/NPTrajectoryPlanner#695]
I could not find any information in the documentation about how pinpoint could be used to export the channel map for a probe between each site, its coordinates, and the brain region of that site.

Can this information be exported?

**Comment by dbirman** [comment]
This button in the top right of the "API" tab in the settings should give you the information you want, it copies to the clipboard and then you need to paste that into a text file.

![image](https://github.com/VirtualBrainLab/Pinpoint/assets/7455770/8105ed6c-e1ff-44e0-975f-78bcea36d984)

We have an in-progress Python API that we're hoping to roll out later this year as well, but for now copying that information to clipboard is the simplest thing you can do.

**Comment by timsainb** [comment]
This is exactly what I was looking for, thanks!
