### ISSUE TITLE
Changing rotation by text works but changing translation by text does not

### ISSUE THREAD

**Issue by bendichter** [VirtualBrainLab/NPTrajectoryPlanner#739]
https://github.com/user-attachments/assets/137e61a5-0fd9-461d-b858-f52dfc9359ae

**Comment by kjy5** [comment]
Hi Ben,
You must confirm by pressing <kbd>Enter</kbd> on your keyboard to enter positions. This is because we recompute your AP, ML, and DV coordinates to be a surface coordinate on the brain and a depth into the brain.

Let us know if this fixes your problem!

**Comment by bendichter** [comment]
@kjy5 yes, that works. Thank you! Sorry for the noise
